"""empty message

Revision ID: 28889b539817
Revises: None
Create Date: 2015-07-06 19:33:58.477922

"""

# revision identifiers, used by Alembic.
revision = '28889b539817'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searches2')
    op.drop_table('searches1')
    op.drop_table('filestable1')
    op.drop_table('filestable2')
    op.drop_table('user1')
    op.drop_table('selected2')
    op.drop_table('filestable3')
    op.drop_table('selected1')
    op.drop_table('searches')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'searches_pkey')
    )
    op.create_table('selected1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time_of_request', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'selected1_pkey')
    )
    op.create_table('filestable3',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filetype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mediatype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'filestable3_pkey')
    )
    op.create_table('selected2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('term_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time_of_request', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'selected2_pkey')
    )
    op.create_table('user1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'user1_pkey')
    )
    op.create_table('filestable2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filetype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mediatype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'filestable2_pkey')
    )
    op.create_table('filestable1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filetype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'filestable1_pkey')
    )
    op.create_table('searches1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'searches1_pkey')
    )
    op.create_table('searches2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time_of_search', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'searches2_pkey')
    )
    ### end Alembic commands ###
